name: deploy-config
on:
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Copy files
        uses: ulaval/azure-blob-copy-action@v1
        with:
          action: upload
          connection_string: ${{ secrets.CONNECTION_STRING }}
          container_name: "aditya-test"
          local_directory: "dev/config.js"
          blob_directory: "."
          http_headers: |
            - glob: "**/*.????????.*"
              headers:
                Cache-Control: public, max-age=604800, immutable

            - glob: "**.*"
              headers:
                Cache-Control: public, max-age=120, s-maxage=180, proxy-revalidate
